import inventory from './src/data/inventory.json' assert { type: 'json' };
import engine from './src/utils/RecommendationEngine.js';

const results = engine.recommend(inventory, { searchQuery: 'moonshine' });

const comparable = results.filter(r => r.matchType === 'comparable');

console.log('Comparables Generated by Engine:', comparable.length);
if(comparable.length > 0) {
    comparable.slice(0, 5).forEach(c => console.log('ALT:', c.name, 'Type:', c.liquorType, 'Cat:', c.category));
}
